#!/usr/bin/env python3
"""Generate fixed-point (16.16) sine table for the software 3D engine."""
import math, sys
N=256
out=sys.argv[1] if len(sys.argv)>1 else "src/sintab.inc"
with open(out,"w") as f:
    f.write("/* Generated by tools/gen_tables.py - 256-entry 16.16 sine table. */\n")
    f.write("static const int sintab[256] = {\n")
    for i in range(N):
        v=int(round(math.sin(i/N*2*math.pi)*65536))
        f.write(f"{v},")
        if i%8==7: f.write("\n")
    f.write("};\n")
print("wrote",out)

# --- reciprocal table for projection (appended) ---
import sys as _sys
if len(_sys.argv) > 2:
    out2 = _sys.argv[2]
    N2 = 4096                 # covers camera-z from ~0.06 .. many units (12.4 fixed key)
    SH = 22                   # recip stored as (1<<SH)/z_key
    with open(out2, "w") as f:
        f.write("/* Generated: reciprocal table. recip[k] ~= (1<<%d)/k, k = z>>12 (12.4). */\n" % SH)
        f.write("#define RECIP_SH %d\n" % SH)
        f.write("#define RECIP_N %d\n" % N2)
        f.write("static const unsigned int recip_tab[%d] = {\n" % N2)
        for k in range(N2):
            v = 0 if k == 0 else int((1 << SH) / k)
            f.write("%d," % v)
            if k % 12 == 11: f.write("\n")
        f.write("};\n")
    print("wrote", out2)
